services:
  db:
    image: postgres:16-alpine

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5433:5432"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped


  app:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    environment:
      DB_HOST: db
      DB_PORT: 5432

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    restart: unless-stopped


  loader:
    build:
      context: .
      dockerfile: Dockerfile

    command:
      [
        "python",
        "-m",
        "scripts.load_data"
      ]

    env_file:
      - .env

    environment:
      DB_HOST: db
      DB_PORT: 5432

    volumes:
      - ./data/raw:/app/data/raw:ro

    depends_on:
      db:
        condition: service_healthy

    profiles:
      - tools


volumes:
  postgres_data: